[project]
name = "passlair-crypto"
version = "0.1.0"
description = "Library for python, that allows hashing and encryption of passwords."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "maturin>=1.14.1",
]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
binding = "pyo3"
python-source = "python"
module-name = "passlair_crypto.package"

[tool.basedpyright]
include = ["python"]
pythonVersion = "3.14"
pythonPlatform = "All"
venvPath = "."
venv = ".venv"
typeCheckingMode = "strict"
reportUnnecessaryTypeIgnoreComment = "warning"
